### ISSUE TITLE
AWS Lambda does not support Runtime: nodejs8.10

### ISSUE THREAD

**Issue by ajaybharti4u** [danil-smirnov/logs-insights-to-metric#1]
Hi Danil,

I was looking to leverage this application to generate custom metric but I am unable to deploy this code as AWS doesn't support Runtime: nodejs8.10.

**Comment by danil-smirnov** [comment]
Hi @ajaybharti4u 
I've just released a new version 1.1.0 and published it to the AWS Serverless Application Repository.
